### ISSUE TITLE
Could not find a version that satisfies the requirement wxPython

### ISSUE THREAD

**Issue by brunohanai** [kendricktan/endless-nn#1]
Hi,

Thanks for this repo!

I tried to run `sudo pip install -r requirements.txt` but got the following error: 

> "Could not find a version that satisfies the requirement wxPython==3.0.2.0"

I'm using Linux, but [this link about Windows][1] may have some info about that error. Maybe you want to check it to update the README.

So I proceed with these steps:

1. Installed Linux requisites from [this link][2] (with `apt install`)
2. Run `sudo pip install --upgrade --trusted-host wxpython.org --pre -f http://wxpython.org/Phoenix/snapshot-builds/wxPython_Phoenix` (from [this link][3])

But I'm not able to start the Endless Lake and don't know why. The game "load" but don't start.

I don't know if it is related with my browser (missing some plugin) or related with my country (Brazil). Anyway, thank you, I can check your code and try to understand something.

[1]: https://github.com/pypa/pip/issues/3627
[2]: https://github.com/wxWidgets/Phoenix/blob/master/README.rst#prerequisites
[3]: https://wiki.wxpython.org/How%20to%20install%20wxPython#GNU.2FLinux_-_Debian

**Comment by kendricktan** [comment]
Hi there,

I myself had troubles installing `wx`
What I did was manually type in `pip install wx` in order for it to work.

**Comment by brunohanai** [comment]
Ok, thanks. `pip install wx` seems to work too.

And I solved my personal problem collecting data from a YouTube video.

**Comment by hensal** [comment]
while running this command:    pip install wx
Could not find a version that satisfies the requirement wx (from versions: )
No matching distribution found for wx??what is its solution???

**Comment by hmchaitra** [comment]
Hi,
I am also facing the same issue can any1 provide a solution.!!!??

**Comment by xu3352** [comment]
[How to install wxPython](https://wiki.wxpython.org/How%20to%20install%20wxPython)

**Comment by xu3352** [comment]
Windows and macOS 
`pip install -U wxPython`

**Comment by JFLABO** [comment]
thank you!!

**Comment by William-Dunlap** [comment]
I tried all solutions listed above, none of them worked. I downloaded the tar.gz file and untarred it, however when i tried this pycharm could not find it.
